name: Tales of Murder
description: for readers with time to kill!

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalinks: pretty

exclude: ['README.md', 'codekit-config.json', 'config.rb', '.gitignore', '.DS_Store', '.sass-cache']